// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVxvkyTWk5US_U3kvsDZluFz_zviLeAiQ',
    appId: '1:784920165526:web:08af5c65f692a89a8896b7',
    messagingSenderId: '784920165526',
    projectId: 'deep-linking-3d7c2',
    authDomain: 'deep-linking-3d7c2.firebaseapp.com',
    storageBucket: 'deep-linking-3d7c2.appspot.com',
    measurementId: 'G-ZRPGXDWB1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1A8mINF12vgs3KyT4FLqNMDUw8VrlBJY',
    appId: '1:784920165526:android:ae5d575b7e0cf0c68896b7',
    messagingSenderId: '784920165526',
    projectId: 'deep-linking-3d7c2',
    storageBucket: 'deep-linking-3d7c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrnVEFK2bvd6asTQS1ra2BOgkdcSFut_M',
    appId: '1:784920165526:ios:14cdcdd4fe6b840a8896b7',
    messagingSenderId: '784920165526',
    projectId: 'deep-linking-3d7c2',
    storageBucket: 'deep-linking-3d7c2.appspot.com',
    iosBundleId: 'com.example.deepLinking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrnVEFK2bvd6asTQS1ra2BOgkdcSFut_M',
    appId: '1:784920165526:ios:e09b58e1493a56df8896b7',
    messagingSenderId: '784920165526',
    projectId: 'deep-linking-3d7c2',
    storageBucket: 'deep-linking-3d7c2.appspot.com',
    iosBundleId: 'com.example.deepLinking.RunnerTests',
  );
}
